### ISSUE TITLE
Implement Testing Framework with Vitest

### ISSUE THREAD

**Issue by bhouston** [bhouston/mcp-server-text-editor#1]
# Testing Framework Plan Using Vitest

## Overview
This issue outlines a plan to implement a comprehensive testing framework for the mcp-server-text-editor project using Vitest. The testing framework will ensure the reliability and correctness of the text editor functions and MCP server implementation.

## Goals
- Implement unit tests for all text editor functions
- Create integration tests for the MCP server
- Set up test coverage reporting
- Configure CI/CD to run tests automatically

### 1. Setup Vitest

- Install Vitest and related dependencies:
  ```bash
  pnpm add -D vitest @vitest/coverage-v8 @vitest/ui
  ```

- Add test scripts to package.json:
  ```json
  "scripts": {
    "test": "vitest run",
    "test:watch": "vitest",
    "test:ui": "vitest --ui",
    "test:coverage": "vitest run --coverage"
  }
  ```

- Create a vitest.config.ts file:
  ```typescript
  import { defineConfig } from 'vitest/config'

  export default defineConfig({
    test: {
      globals: true,
      environment: 'node',
      coverage: {
        provider: 'v8',
        reporter: ['text', 'json', 'html'],
        exclude: ['**/node_modules/**', '**/dist/**', '**/test/**']
      }
    }
  })
  ```

### 2. Create Test Directory Structure

```
/test
  /unit
    /lib
      getPackageInfo.test.ts
    /tools
      textEditor.test.ts
  /integration
    mcp-server.test.ts
  /fixtures
    sample-files/
      test.txt
      test.js
  /helpers
    fileSystem.ts
```

#### Text Editor Tool Tests

Test each command of the text editor tool:
- `view` command
- `create` command
- `str_replace` command
- `insert` command
- `undo_edit` command

Example test cases:
- Test viewing file contents with and without line ranges
- Test creating new files
- Test replacing text in existing files
- Test inserting text at specific lines
- Test undoing previous edits
- Test error handling for each command

#### Utility Function Tests

Test utility functions like `getPackageInfo.ts`.

### 4. Integration Tests

Test the MCP server implementation:
- Test server startup and initialization
- Test API endpoint handling
- Test request validation
- Test response formatting
- Test error handling

Create mock requests that simulate how Claude would interact with the MCP server.

### 5. Test Fixtures

Create a set of test fixtures:
- Sample text files of different formats (txt, js, ts, etc.)
- Directory structures for testing directory viewing
- Invalid files for testing error handling

### 6. Setup CI/CD Integration

Configure GitHub Actions to:
- Run tests on pull requests
- Run tests on pushes to main branch
- Generate and publish coverage reports

Example GitHub Actions workflow:
```yaml
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
      - run: pnpm test:coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
```

## Timeline

1. Setup Vitest configuration (1 day)
2. Implement unit tests (2-3 days)
3. Implement integration tests (1-2 days)
4. Setup CI/CD integration (1 day)

## Success Criteria

- 80%+ test coverage
- All tests passing in CI/CD
- Documentation for running and writing tests
- Automated test runs on PRs and commits to main

## Next Steps

Once this testing framework is implemented, we can:
1. Add more extensive tests as new features are developed
2. Implement performance testing
3. Add browser-based testing for any future web interfaces
